// Sol Shalom Trading product catalog.
// Source: client spreadsheets (web3.xlsx, web site.xlsx). Photos live in /public/products/<id>-<n>.jpg.
// To add a product: drop its photos in public/products and add an entry below.

export const families = ["Seating", "Desks & Tables", "Storage", "Lounge"];

export const categories = [
	{ id: "executive-chairs", name: "Executive Chairs", family: "Seating", blurb: "Ergonomic and leather chairs for managers and executives." },
	{ id: "high-back-chairs", name: "High-Back Chairs", family: "Seating", blurb: "Full-support mesh task chairs and teller stools." },
	{ id: "medium-back-chairs", name: "Medium-Back Chairs", family: "Seating", blurb: "Everyday swivel chairs for staff and secretaries." },
	{ id: "guest-chairs", name: "Guest & Visitor Chairs", family: "Seating", blurb: "Visitor chairs, beam seating and banquet chairs." },
	{ id: "auditorium-chairs", name: "Auditorium Chairs", family: "Seating", blurb: "Folding public seating for halls and cinemas." },
	{ id: "managerial-desks", name: "Managerial Desks", family: "Desks & Tables", blurb: "Executive desks with side returns and locking drawers." },
	{ id: "office-desks", name: "Office & Computer Desks", family: "Desks & Tables", blurb: "Single-pedestal desks and computer tables." },
	{ id: "conference-tables", name: "Conference Tables", family: "Desks & Tables", blurb: "Boardroom tables from 2.4 m to 6 m." },
	{ id: "workstations", name: "Workstations", family: "Desks & Tables", blurb: "Four-person cluster desks with partitions." },
	{ id: "shelves-cabinets", name: "Shelves & Cabinets", family: "Storage", blurb: "Bookshelves, filing cabinets and steel shelving." },
	{ id: "office-sofas", name: "Office Sofas", family: "Lounge", blurb: "Leather sofa sets for receptions and offices." },
	{ id: "coffee-tables", name: "Coffee Tables", family: "Lounge", blurb: "Low tables for waiting areas and lounges." },
];

// Shared feature sets
const ERGONOMIC = [
	"High-elastic mesh back with flex mesh seat",
	"Multi-function adjustable armrests",
	"Synchronised tilt mechanism",
	"Lumbar support adjustable in height and depth",
	"Sliding seat",
	"Aluminium five-star base",
];
const EXEC_MESH = [
	"High-elastic mesh back",
	"Flex fabric seat",
	"Multi-function adjustable armrests",
	"Synchronised tilt mechanism",
	"Lumbar support adjustable in height and depth",
];
const SWIVEL_MESH = [
	"High-quality mesh back",
	"Fixed armrests",
	"Gas-lift seat height adjustment",
	"Strong metal five-star base",
];
const MESH_GUEST = [
	"Mesh back with padded seat",
	"Sledge (cantilever) steel base",
	"Armrests",
];
const CONFERENCE = [
	"High-pressure laminated particle board",
	"PU leather inlay along the centre",
	"Comfortable, durable and suited to daily meetings",
];
const MANAGERIAL = [
	"High-pressure laminated particle board",
	"Side return for printer or files",
	"Central locking system",
	"Keyboard tray, drawer and CPU holder",
];
const COMPUTER_DESK = [
	"High-pressure laminated and melamine board",
	"Three-drawer fixed pedestal",
	"Central locking system",
	"Keyboard drawer and movable CPU holder",
];
const OFFICE_DESK = [
	"25 mm laminated board top and legs",
	"Three-drawer fixed pedestal",
	"Central locking system",
];

const raw = [
	// ── Executive chairs
	{ id: "mcl", code: "MCL", name: "Executive Leather Chair", category: "executive-chairs", photos: 2,
		summary: "A leather executive chair with wooden armrests and a wood-trimmed metal base.",
		features: ["Leather upholstery", "Seat height adjustment", "Fixed (non-tilting) back", "Wooden armrests", "Metal base with wood cover"],
		specs: [] },
	{ id: "q8d", code: "Q8 D", name: "Ergonomic Executive Chair", category: "executive-chairs", photos: 2,
		summary: "A high-back ergonomic chair with full mesh, adjustable lumbar and a sliding seat.",
		features: ERGONOMIC, specs: [["Colour", "Black"]] },
	{ id: "q8", code: "Q8", name: "Ergonomic Executive Chair", category: "executive-chairs", photos: 1,
		summary: "The Q8 high-back ergonomic chair in a single-back version.",
		features: ERGONOMIC, specs: [["Colour", "Black"]] },
	{ id: "937", code: "937", name: "Double-Back Ergonomic Chair", category: "executive-chairs", photos: 1,
		summary: "A high-back ergonomic chair with a split double backrest that follows the spine.",
		features: ["Double (split) mesh backrest", ...ERGONOMIC], specs: [["Colour", "Black"]] },
	{ id: "311", code: "311", name: "Double-Back Ergonomic Chair", category: "executive-chairs", photos: 2,
		summary: "A high-back double-back ergonomic chair with full adjustment.",
		features: ["Double (split) mesh backrest", ...ERGONOMIC], specs: [] },

	// ── High-back chairs
	{ id: "scm-23", code: "SCM-23", name: "Executive High-Back Chair", category: "high-back-chairs", photos: 4,
		summary: "A mesh high-back chair with headrest for long working days.",
		features: EXEC_MESH, specs: [] },
	{ id: "m-35", code: "M-35", name: "Executive High-Back Chair", category: "high-back-chairs", photos: 2,
		summary: "A mesh high-back chair with headrest and multi-function armrests.",
		features: EXEC_MESH, specs: [] },
	{ id: "a01", code: "A01", name: "Mesh High-Back Chair", category: "high-back-chairs", photos: 2,
		summary: "A clean, light-grey mesh chair with headrest.",
		features: EXEC_MESH, specs: [] },
	{ id: "scm-m", code: "SCM", name: "Mesh High-Back Chair", category: "high-back-chairs", photos: 2,
		summary: "An elastic-frame mesh back with a fabric seat and headrest.",
		features: ["Elastic frame covered in mesh", ...EXEC_MESH.slice(1)], specs: [] },
	{ id: "scm-f", code: "SCM", name: "Mesh High-Back Chair", category: "high-back-chairs", photos: 2,
		summary: "The SCM high-back chair with a full mesh back.",
		features: EXEC_MESH, specs: [] },
	{ id: "m-33", code: "M-33", name: "Executive High-Back Chair", category: "high-back-chairs", photos: 1,
		summary: "A mesh executive chair with headrest and synchronised tilt.",
		features: EXEC_MESH, specs: [] },
	{ id: "mcl-b", code: "MCL", name: "Executive Leather Chair (Black)", category: "high-back-chairs", photos: 2,
		summary: "A ribbed leather high-back chair on a chrome base.",
		features: ["Leather upholstery", "Seat height adjustment", "Fixed (non-tilting) back", "Chrome base"],
		specs: [["Colour", "Black"]] },
	{ id: "ts-17", code: "TS-17", name: "Teller Stool — Mesh", category: "high-back-chairs", photos: 2,
		summary: "A tall swivel stool for bank counters and reception desks.",
		features: ["Mesh back", "Upholstered seat", "Adjustable seat height", "Armrests", "Foot ring"], specs: [] },
	{ id: "ts-17f", code: "TS-17F", name: "Teller Stool — Fabric", category: "high-back-chairs", photos: 2,
		summary: "The TS-17 teller stool with fabric back and seat.",
		features: ["Fabric back and seat", "Adjustable seat height", "Armrests", "Foot ring"], specs: [] },

	// ── Medium-back chairs
	{ id: "701", code: "701", name: "Mesh Swivel Chair", category: "medium-back-chairs", photos: 2,
		summary: "A reliable mesh swivel chair for staff desks.",
		features: SWIVEL_MESH, specs: [] },
	{ id: "701a", code: "701A", name: "Secretary Chair", category: "medium-back-chairs", photos: 1,
		summary: "A compact mesh chair for secretaries and front desks.",
		features: SWIVEL_MESH, specs: [] },
	{ id: "scm-mb", code: "SCM", name: "Executive Medium-Back Chair", category: "medium-back-chairs", photos: 1,
		summary: "A medium-back mesh chair with full adjustment.",
		features: EXEC_MESH, specs: [["Colour", "Black"]] },
	{ id: "scm-12", code: "SCM-12", name: "Executive Medium-Back Chair", category: "medium-back-chairs", photos: 2,
		summary: "A medium-back mesh chair with lumbar support.",
		features: EXEC_MESH, specs: [["Colour", "Black"]] },
	{ id: "m-03", code: "M-03", name: "Executive Medium-Back Chair", category: "medium-back-chairs", photos: 1,
		summary: "A medium-back mesh chair with multi-function armrests.",
		features: EXEC_MESH, specs: [["Colour", "Black"]] },
	{ id: "mf-01", code: "MF-01", name: "Fabric Swivel Chair", category: "medium-back-chairs", photos: 1,
		summary: "A medium-back swivel chair upholstered in fabric.",
		features: ["Full fabric upholstery", "Adjustable seat height", "Gas-lift system", "Five-star base with strong castors"], specs: [] },

	// ── Guest chairs
	{ id: "840c", code: "840C", name: "Mesh Guest Chair", category: "guest-chairs", photos: 4,
		summary: "A mesh visitor chair on a sledge base.",
		features: MESH_GUEST,
		specs: [["Back", "48 H × 52 W cm"], ["Seat", "50 W × 50 D cm"], ["Overall height", "100 cm"]] },
	{ id: "6019", code: "6019", name: "Mesh Guest Chair", category: "guest-chairs", photos: 3,
		summary: "A mesh visitor chair with a wide back.",
		features: MESH_GUEST,
		specs: [["Back", "45 H × 55 W cm"], ["Seat", "48 W × 48 D cm"], ["Overall height", "95 cm"]] },
	{ id: "b800", code: "B800", name: "Mesh Guest Chair", category: "guest-chairs", photos: 2,
		summary: "A black mesh visitor chair on a sledge base.",
		features: MESH_GUEST, specs: [["Colour", "Black"]] },
	{ id: "701-g", code: "701/G", name: "Mesh Guest Chair", category: "guest-chairs", photos: 2,
		summary: "The visitor version of the 701 chair.",
		features: MESH_GUEST,
		specs: [["Back", "45 H × 48 W cm"], ["Seat", "50 W × 45 D cm"], ["Overall height", "90 cm"]] },
	{ id: "m03g", code: "M03G", name: "Mesh Guest Chair", category: "guest-chairs", photos: 2,
		summary: "The visitor chair that matches the M-03 range.",
		features: MESH_GUEST, specs: [] },
	{ id: "scm-g", code: "SCM-G", name: "Mesh Guest Chair", category: "guest-chairs", photos: 4,
		summary: "The visitor chair that matches the SCM range, with a tall back.",
		features: MESH_GUEST,
		specs: [["Back", "50 H × 57 W cm"], ["Seat", "50 W × 50 D cm"], ["Overall height", "100 cm"]] },
	{ id: "gfu", code: "GFU", name: "Fabric Guest Chair", category: "guest-chairs", photos: 2,
		summary: "A fabric visitor chair with arms on a sledge base.",
		features: ["Fabric seat and back", "Armrests", "Black powder-coated sledge base"], specs: [] },
	{ id: "gfm", code: "GFM", name: "Fabric Guest Chair", category: "guest-chairs", photos: 1,
		summary: "A fabric visitor chair on a metal frame.",
		features: ["Fabric upholstery", "Metal frame and legs"], specs: [["Colour", "Black"]] },
	{ id: "gfa", code: "GFA", name: "Fabric Guest Chair with Arms", category: "guest-chairs", photos: 1,
		summary: "A plywood-shell visitor chair with fabric and armrests.",
		features: ["Plywood seat and back covered in fabric", "Armrests", "Four black powder-coated steel legs", "Rubber feet"], specs: [] },
	{ id: "gf", code: "GF", name: "Fabric Guest Chair", category: "guest-chairs", photos: 1,
		summary: "A simple fabric visitor chair on a metal frame.",
		features: ["Fabric upholstery", "Metal frame and legs"], specs: [["Colour", "Black"]] },
	{ id: "s-m-08", code: "S-M-08", name: "Sheraton Banquet Chair", category: "guest-chairs", photos: 1,
		summary: "A first-grade banquet chair for halls, hotels and events.",
		features: [
			"Frame of 22 mm steel tube, 2 mm wall",
			"High-density foam on 9 mm formed plywood",
			"Fabric seat and back",
			"Scratch-resistant powder coating",
			"Rubber feet",
		],
		specs: [["Back", "40 H × 50 W cm"], ["Seat", "40 W × 40 D cm"], ["Overall height", "90 cm"]] },
	{ id: "ya-19b", code: "YA-19B", name: "Three-Seater Beam Chair", category: "guest-chairs", photos: 1,
		summary: "Steel beam seating for waiting areas and banks.",
		features: ["Three seats on one beam", "Chrome-painted steel frame"], specs: [["Seats", "3"]] },
	{ id: "ya-19p", code: "YA-19P", name: "Three-Seater Beam Chair — PU", category: "guest-chairs", photos: 1,
		summary: "Beam seating with PU-covered seats.",
		features: ["Three seats on one beam", "PU leather upholstery", "Chrome-painted steel frame"],
		specs: [["Seats", "3"], ["Colour", "Black"]] },
	{ id: "3gf-07", code: "3GF-07", name: "Three-Seater Fabric Beam Chair", category: "guest-chairs", photos: 1,
		summary: "Fabric beam seating on a metal frame.",
		features: ["Three fabric seats", "Metal frame and legs"],
		specs: [["Seat size", "43 D × 55 W × 75 H cm"], ["Colour", "Black and grey"]] },

	// ── Auditorium
	{ id: "chc78", code: "CHC78", name: "Auditorium Chair", category: "auditorium-chairs", photos: 2,
		summary: "A folding public chair with writing pad for halls and cinemas.",
		features: [
			"Folding seat with serpentine springs",
			"Hardwood (beech or oak) armrests with writing pad",
			"Padded outer back panel",
			"12 mm multi-layer plywood seat pan",
		],
		specs: [
			["Back cushion", "120 mm, foam 55 ± 5 kg/m³"],
			["Seat cushion", "Foam 60 ± 5 kg/m³"],
			["Armrest", "30 mm hardwood"],
		] },

	// ── Managerial desks
	{ id: "mt-240", code: "MT-240", name: "Managerial Desk", category: "managerial-desks", photos: 1,
		summary: "Our largest executive desk, with side return and digital locking.",
		features: ["Digital central locking system", ...MANAGERIAL.filter((f) => !f.startsWith("Central"))],
		specs: [["Main table", "240 × 100 × 75 cm"], ["Side table", "120 × 45 × 65 cm"]] },
	{ id: "mt-200", code: "MT-200", name: "Managerial Desk", category: "managerial-desks", photos: 1,
		summary: "An executive desk with side return and digital locking.",
		features: ["Digital central locking system", ...MANAGERIAL.filter((f) => !f.startsWith("Central"))],
		specs: [["Main table", "200 × 100 × 75 cm"], ["Side table", "120 × 45 × 65 cm"]] },
	{ id: "mt-180", code: "MT-180", name: "Managerial Desk", category: "managerial-desks", photos: 1,
		summary: "An executive desk with side return.",
		features: MANAGERIAL,
		specs: [["Main table", "180 × 90 × 75 cm"], ["Side table", "120 × 45 × 65 cm"]] },
	{ id: "7518", code: "7518", name: "Managerial Desk", category: "managerial-desks", photos: 0,
		summary: "An executive desk with side return and a mobile pedestal.",
		features: [...MANAGERIAL, "Three-drawer mobile pedestal"],
		specs: [["Main table", "180 × 90 × 75 cm"], ["Side table", "120 × 45 × 65 cm"]] },
	{ id: "mt-160", code: "MT-160", name: "Managerial Desk", category: "managerial-desks", photos: 1,
		summary: "A compact executive desk with side return.",
		features: MANAGERIAL,
		specs: [["Main table", "160 × 80 × 75 cm"], ["Side table", "120 × 45 × 65 cm"]] },
	{ id: "9316-2", code: "9316/2", name: "Managerial Desk", category: "managerial-desks", photos: 1,
		summary: "An executive desk with side return.",
		features: MANAGERIAL,
		specs: [["Main table", "160 × 80 × 75 cm"], ["Side table", "120 × 45 × 65 cm"]] },
	{ id: "9316", code: "9316", name: "Managerial Desk — Leather Top", category: "managerial-desks", photos: 1,
		summary: "An executive desk with a leather inlay and mobile pedestal.",
		features: ["Leather inlay on the desktop", ...MANAGERIAL, "Three-drawer mobile pedestal"],
		specs: [["Main table", "160 × 80 × 75 cm"], ["Side table", "120 × 45 × 65 cm"]] },

	// ── Office & computer desks
	{ id: "ctq-120", code: "CTQ-120", name: "Computer Desk", category: "office-desks", photos: 1,
		summary: "A computer desk with lockable drawers and CPU holder.",
		features: COMPUTER_DESK, specs: [["Size", "120 × 60 × 75 cm"]] },
	{ id: "ctq-140", code: "CTQ-140", name: "Computer Desk", category: "office-desks", photos: 1,
		summary: "A wider computer desk with lockable drawers and CPU holder.",
		features: COMPUTER_DESK, specs: [["Size", "140 × 70 × 75 cm"]] },
	{ id: "ctw-120", code: "CTW-120", name: "Wooden Computer Table", category: "office-desks", photos: 1,
		summary: "A laminated computer table with keyboard tray.",
		features: ["Laminated board", "Keyboard tray", "PC holder"], specs: [["Size", "120 × 60 × 75 cm"]] },
	{ id: "otq-120", code: "OTQ-120", name: "Single-Pedestal Office Desk", category: "office-desks", photos: 1,
		summary: "A staff desk with a lockable three-drawer pedestal.",
		features: ["High-pressure laminated and melamine board", ...OFFICE_DESK], specs: [["Size", "120 × 60 × 75 cm"]] },
	{ id: "ot140", code: "OT140", name: "Single-Pedestal Office Desk", category: "office-desks", photos: 2,
		summary: "A wide staff desk with a lockable three-drawer pedestal.",
		features: OFFICE_DESK, specs: [["Size", "140 × 70 × 75 cm"]] },

	// ── Conference tables
	{ id: "yc6", code: "YC6", name: "Conference Table — 6 m", category: "conference-tables", photos: 1,
		summary: "A boardroom table for large meeting rooms.",
		features: CONFERENCE, specs: [["Size", "600 × 150 × 75 cm"]] },
	{ id: "yc48", code: "YC48", name: "Conference Table — 4.8 m", category: "conference-tables", photos: 1,
		summary: "A boardroom table for mid-size meeting rooms.",
		features: CONFERENCE, specs: [["Size", "480 × 150 × 75 cm"]] },
	{ id: "yc036", code: "YC036", name: "Conference Table — 3.6 m", category: "conference-tables", photos: 1,
		summary: "A conference table for team meeting rooms.",
		features: CONFERENCE, specs: [["Size", "360 × 120 × 75 cm"]] },
	{ id: "yc32", code: "YC32", name: "Conference Table — 3.2 m", category: "conference-tables", photos: 1,
		summary: "A conference table for team meeting rooms.",
		features: CONFERENCE, specs: [["Size", "320 × 120 × 75 cm"]] },
	{ id: "yc03", code: "YC03", name: "Conference Table — 2.4 m", category: "conference-tables", photos: 1,
		summary: "A compact conference table for small meeting rooms.",
		features: CONFERENCE, specs: [["Size", "240 × 120 × 75 cm"]] },

	// ── Workstations
	{ id: "pt-240", code: "PT-240", name: "Four-Person L-Shape Workstation", category: "workstations", photos: 1,
		summary: "An all-wood cluster of four L-shaped desks with partitions.",
		features: ["Seats four people", "Wooden partitions between desks", "Three-drawer fixed pedestals", "Keyboard trays", "Movable CPU holders"],
		specs: [["Size", "240 × 240 × 75 cm"]] },
	{ id: "gt-240-120", code: "GT-240/120", name: "Four-Person Partition Table", category: "workstations", photos: 1,
		summary: "Laminated desks on an aluminium frame for four people.",
		features: ["Seats four people", "Laminated board on aluminium frame", "Mobile drawer, keyboard tray and CPU holder at every seat"],
		specs: [["Size", "240 × 120 cm"]] },

	// ── Shelves & cabinets
	{ id: "a3", code: "A3", name: "Three-Door Bookshelf", category: "shelves-cabinets", photos: 1,
		summary: "A wooden bookshelf with glass doors above and lockable doors below.",
		features: ["High-pressure laminated particle board", "Three lockable glass doors above", "Three lockable wooden doors below", "Adjustable shelves"],
		specs: [["Size", "200 × 120 × 40 cm"]] },
	{ id: "a2", code: "A2", name: "Two-Door Bookshelf", category: "shelves-cabinets", photos: 1,
		summary: "A narrower wooden bookshelf with glass and wooden doors.",
		features: ["High-pressure laminated particle board", "Two lockable glass doors above", "Two lockable wooden doors below", "Adjustable shelves"],
		specs: [["Size", "200 × 80 × 40 cm"]] },
	{ id: "w-09-16", code: "W-09-16", name: "Steel Cupboard", category: "shelves-cabinets", photos: 1,
		summary: "A lockable two-door steel filing cupboard.",
		features: ["Sheet-metal construction", "Two lockable doors", "Four adjustable steel shelves", "Light grey finish"],
		specs: [["Size", "180 × 80 × 37 cm"]] },
	{ id: "w-09-10", code: "W-09-10", name: "Half-Glass Steel Bookshelf", category: "shelves-cabinets", photos: 1,
		summary: "A steel bookshelf with glass doors on top.",
		features: ["Steel construction", "Two glass doors on top", "Two steel doors below"],
		specs: [["Size", "180 × 80 × 40 cm"]] },
	{ id: "w-134d", code: "W-134D", name: "Four-Drawer Filing Cabinet", category: "shelves-cabinets", photos: 1,
		summary: "A steel filing cabinet with four drawers on ball-bearing runners.",
		features: ["Four drawers", "Central locking system", "Ball-bearing drawer runners", "Light grey finish"],
		specs: [["Size", "62 W × 46 D × 134 H cm"]] },
	{ id: "dsm-200", code: "DSM-200", name: "Open Steel Shelving", category: "shelves-cabinets", photos: 1,
		summary: "Open steel shelving for stores and archives.",
		features: ["Five shelf levels", "Open steel frame"], specs: [["Size", "200 × 80 × 40 cm"]] },

	// ── Office sofas
	{ id: "sofa7", code: "SOFA7", name: "Office Sofa Set — 7 Seats", category: "office-sofas", photos: 1,
		summary: "A leather reception set with wooden arms and legs.",
		features: ["Leather seats and backrests", "Wooden legs and armrests"], specs: [["Set", "3 + 2 + 1 + 1 seats"]] },
	{ id: "sofa5", code: "SOFA5", name: "Office Sofa Set — 5 Seats", category: "office-sofas", photos: 1,
		summary: "A leather reception set for smaller offices.",
		features: ["Leather seats and backrests", "Wooden legs and armrests"], specs: [["Set", "3 + 1 + 1 seats"]] },

	// ── Coffee tables
	{ id: "cft-120", code: "CFT 120", name: "Coffee Table", category: "coffee-tables", photos: 0,
		summary: "A wooden coffee table with magazine shelf.",
		features: ["Wooden construction", "Magazine holder"], specs: [["Size", "120 × 60 × 45 cm"]] },
	{ id: "cft-60", code: "CFT 60", name: "Square Coffee Table", category: "coffee-tables", photos: 0,
		summary: "A square MDF coffee table with magazine shelf.",
		features: ["MDF construction", "Magazine holder"], specs: [["Size", "60 × 60 × 45 cm"]] },
];

export const products = raw.map(({ photos, ...p }) => ({
	...p,
	images: Array.from({ length: photos }, (_, i) => `/products/${p.id}-${i + 1}.jpg`),
}));

export const getProduct = (id) => products.find((p) => p.id === id);
export const getCategory = (id) => categories.find((c) => c.id === id);
export const productsIn = (categoryId) => products.filter((p) => p.category === categoryId);
